import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Roboto } from 'next/font/google'


const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'], 
  display: 'swap',
  variable: '--font-roboto', 
})




export const metadata = {
  title: "MENTRIC TECHNOLOGIES",
  description: "Generated by create next app",
  icons: {
    icon: "/mentric.jpg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body
        className={`${roboto.variable}  antialiased overflow-x-hidden `}
      >
        {children}
      </body>
    </html>
  );
}
